### ISSUE TITLE
background-color

### ISSUE THREAD

**Issue by GeorgeKrasnoschekov** [rehfres/decorator-sample#1]
Is it possible to get background-color besides color of colored console.log messages? Or how can i do it?
For example like this:
![background console code](https://user-images.githubusercontent.com/44648386/64867047-4463f600-d645-11e9-8188-2be920eaaf85.png)
result: 
![background console](https://user-images.githubusercontent.com/44648386/64866892-fcdd6a00-d644-11e9-9066-93ebda2f52af.png)

**Comment by rehfres** [comment]
Hi, I'll think about it.
The key is in this line: 
`let pattern = /console.log\('%c.*', 'color: (#([a-f0-9]{6}(?:[a-f0-9]{0,2}))\b)/g` in the "src/extension.ts" file. 
You will need to replace it with 
`let pattern = /console.log\('%c.*', 'background: (#([a-f0-9]{6}(?:[a-f0-9]{0,2}))\b)/g`,
and also in the `insertConsoleLog` function change this line:
**let insertText = type === 'primitive' ? `\n${spaceee}console.log('%c${sss}', 'color: ${newColor()}', ${selectedText});`**
 to the one you want - with background and color: white.

There might also be issues with the calculation of lines and columns.
As I said I don't really have much time for it right now, I will probably get back to it when I have some.

Hope you figure it out by then. If not, come back - I'll try to help some more
